# Generated by Django 3.0.4 on 2020-04-29 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='owner',
        ),
    ]
